version: "3.7"

services:
  backend:
    restart: unless-stopped
    container_name: backend
    image: docker.pkg.github.com/paulords95/nova-dax-api/nova-dax-api:latest
    networks:
      - public_01
    ports:
      - 9433:9433
    volumes:
      - ./.env:/home/.env

networks:
  public_01:
