name: Deploy
on: [workflow_dispatch]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run
        env:
          SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no ./docker-compose.yml root@$SERVER_IP:/root/nova-dax-api
          ssh -o StrictHostKeyChecking=no root@$SERVER_IP "echo '${{ secrets.GITHUB_TOKEN }}' | sudo docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin && sudo docker-compose pull && docker-compose down && docker-compose up -d"
